import type { NextPage, GetStaticProps, InferGetStaticPropsType } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { buildClient, PropertyFields } from '../lib/contentful';
import Link from 'next/link';
import { Entry, EntryCollection } from 'contentful';
import Image from 'next/image';

const client = buildClient();

client
	.getAssets()
	.then((response) => console.log(response.items))
	.catch(console.error);

export const getStaticProps: GetStaticProps = async () => {
	const { items }: EntryCollection<PropertyFields> = await client.getEntries({
		content_type: 'propertyManagement',
		order: '-sys.createdAt',
	});
	return {
		props: { properties: items },
	};
};

type Props = InferGetStaticPropsType<typeof getStaticProps>;

const Home: NextPage<Props> = ({ properties }) => {
	console.log(properties);

	return (
		<div className={styles.container}>
			<Head>
				<title>Property management prototype</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<h1 className={styles.title}>北前住宅</h1>
				<Image src='/assets/NavLogo.png' width={60} height={60} alt='logo' />
				<div>
					<ul>
						{properties &&
							properties.map((property: Entry<PropertyFields>) => (
								<li key={property.sys.id}>
									<Link href={property.fields.slug}>
										<h2>{property.fields.propertyTitle}</h2>
									</Link>
								</li>
							))}
					</ul>
				</div>
			</main>
		</div>
	);
};

export default Home;
